version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # If pom.xml is at repo root; adjust path if needed
    schedule:
      interval: "daily" # or "weekly" for less frequency
    allow:
      - dependency-name: "com.regnosys.rosetta:com.regnosys.rosetta"
      - dependency-name: "com.regnosys.rosetta:com.regnosys.rosetta.lib"
      - dependency-name: "com.regnosys.rosetta:com.regnosys.rosetta.tests"
