name: Build and Test (Reusable)

on:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build with Maven
        run: mvn -B package -Psign-artifacts --file pom.xml
      - name: Run Python Unit Tests
        run: |
          chmod +x test/python_setup/setup_python_env.sh
          chmod +x test/python_setup/cleanup_python_env.sh
          chmod +x test/python_unit_tests/setup_unit_test_env.sh
          chmod +x test/python_unit_tests/run_python_unit_tests.sh
          test/python_unit_tests/run_python_unit_tests.sh