# .github/workflows/ci-develop.yml

name: CI - Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

concurrency:
  group: ci-develop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      java-version: '21'
      python-version: '3.11'
