name: Test on Dependabot PRs

on:
  pull_request:
    paths:
      - 'pom.xml'
    branches:
      - main
      - master # Adjust as appropriate

jobs:
  test:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B clean verify