# .github/workflows/release-on-tag.yml

name: Release on tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Extract version from tag name (e.g., 'rosetta-dsl-v1.2.3' -> '1.2.3')
          RELEASE_VERSION=${TAG_NAME#rosetta-dsl-v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Call core release workflow
        uses: ./.github/workflows/release-core.yml
        with:
          release_version: ${{ steps.get_tag.outputs.release_version }}