# .github/workflows/release-on-tag.yml

name: Release on tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: ./.github/workflows/release-core.yml
    with:
      release_version: ${{ github.ref_name }}
