# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - '*' # Trigger on any tag push

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true


jobs:
  # 1. Reuse the core build-and-test workflow
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      java-version: '21'
      python-version: '3.11'

  # 2. Release job — runs only if build/test succeeds
  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          RELEASE_VERSION=${TAG_NAME#rosetta-dsl-v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Release Artifacts
        run: mvn -B clean package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          name: Release ${{ steps.get_tag.outputs.release_version }}
          body: |
            Automated release for version ${{ steps.get_tag.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
