# .github/workflows/renovate.yml
name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          # The relevant line to enable debug logging:
          LOG_LEVEL: 'debug'          
